#!/bin/bash
#
# build_batch_analysis.sh
# ────────────────────────────────────────────────────────────────────────────
# Generate batch-specific phylogenetic trees and SNP distance matrices from
# per-sequence analysis data (generated by build_per_seq_trees.sh).
#
# Usage: bash build_batch_analysis.sh <batch_dir> <dataset_date> <output_dir>
#
# Arguments:
#   batch_dir      Path to batch directory (for context only)
#   dataset_date   Dataset date in format YYYY-MM-DD
#   output_dir     Output base directory (should be <batch>/output from run_all_analyses.sh)
#
# Prerequisites:
#   - build_per_seq_trees.sh must have completed first
#   - Per-sequence trees in: <output_dir>/trees/<seqName>/
#   - Each must contain: aligned_trimmed_blast_only.fa
#
# Dependencies:
#   - MAFFT (multiple sequence alignment)
#   - IQ-TREE (phylogenetic tree inference)
#   - R with ape package (SNP distance calculation)
#
# Output:
#   - <output_dir>/trees/batch/batch.aligned.fasta (batch alignment)
#   - <output_dir>/trees/batch/tree.treefile       (phylogenetic tree)
#   - <output_dir>/snp_matrices/batch_snp_distances.tsv (SNP distance matrix)
#
# ────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# Parse arguments
BATCH_DIR="${1:?ERROR: batch_dir not provided}"
DATASET_DATE="${2:?ERROR: dataset_date not provided}"
OUTPUT_DIR="${3:?ERROR: output_dir not provided}"

# Verify batch directory
if [[ ! -d "$BATCH_DIR" ]]; then
    echo "ERROR: Batch directory not found: $BATCH_DIR"
    exit 1
fi

# Setup output directories
# OUTPUT_DIR is already the output base (e.g., batch_dir/output from run_all_analyses.sh)
BATCH_OUTPUT="$OUTPUT_DIR"
BATCH_TREES="$BATCH_OUTPUT/trees/batch"
BATCH_SNP="$BATCH_OUTPUT/snp_matrices"

mkdir -p "$BATCH_TREES" "$BATCH_SNP"

echo "================================================"
echo "Building batch-specific analyses"
echo "================================================"
echo "Batch directory: $BATCH_DIR"
echo "Dataset date: $DATASET_DATE"
echo "Output directory: $BATCH_TREES"
echo ""

# ────────────────────────────────────────────────────────────────────────────
# Step 1: Collect batch query sequences from per-sequence aligned files
# ────────────────────────────────────────────────────────────────────────────

echo "Step 1: Collecting batch sequences..."

# Discover sequence IDs from per-sequence trees directory
# After build_per_seq_trees.sh, all per-sequence outputs are in BATCH_OUTPUT/trees/<seqName>/
PER_SEQ_TREES="$BATCH_OUTPUT/trees"

if [[ ! -d "$PER_SEQ_TREES" ]]; then
    echo "ERROR: Per-sequence trees directory not found: $PER_SEQ_TREES"
    echo "Please run build_per_seq_trees.sh first"
    exit 1
fi

# List all directories in trees/ to get sequence IDs (excluding batch subdirectory)
BATCH_SEQS=$(ls -1d "$PER_SEQ_TREES"/*/ 2>/dev/null | xargs -n1 basename | grep -v "^batch$" | sort -u)

if [[ -z "$BATCH_SEQS" ]]; then
    echo "ERROR: No per-sequence tree directories found in $PER_SEQ_TREES"
    exit 1
fi

SEQ_COUNT=$(echo "$BATCH_SEQS" | wc -l)
echo "Found $SEQ_COUNT batch sequences from per-sequence trees"
echo "Debug: Per-sequence trees at: $PER_SEQ_TREES"
echo ""

# List found directories for debugging
echo "Found sequence directories:"
ls -1d "$PER_SEQ_TREES"/*/ 2>/dev/null | xargs -n1 basename | grep -v "^batch$"
echo ""

# Create temporary batch alignment file
BATCH_ALIGN_TMP="$BATCH_TREES/batch_alignment_tmp.fa"
> "$BATCH_ALIGN_TMP"

ALIGN_COUNT=0

for seq_id in $BATCH_SEQS; do
    SEQ_ALN_FILE="$PER_SEQ_TREES/$seq_id/aligned_trimmed_blast_only.fa"
    echo "Processing: $seq_id"
    
    if [[ ! -f "$SEQ_ALN_FILE" ]]; then
        echo "  ✗ Alignment file NOT found: $SEQ_ALN_FILE"
        echo "    Checking directory contents:"
        if [[ -d "$PER_SEQ_TREES/$seq_id" ]]; then
            ls -la "$PER_SEQ_TREES/$seq_id/"
        else
            echo "    Directory doesn't exist!"
        fi
        continue
    fi
    
    echo "  ✓ Found alignment file"
    echo "  → Starting extraction..."
    
    # Temporarily disable pipefail for sequence extraction
    set +o pipefail
    
    # Extract first FASTA sequence using awk
    # Print renamed header on first line, then all sequence lines until next header
    echo "  → Running extraction command..."
    
    awk -v seqid="$seq_id" '
        /^>/ {
            if (first_header_seen) exit
            print ">" seqid
            first_header_seen = 1
            next
        }
        first_header_seen { print }
    ' "$SEQ_ALN_FILE" >> "$BATCH_ALIGN_TMP" 2>&1
    
    EXTRACT_EXIT=$?
    echo "  → Extraction exited with code: $EXTRACT_EXIT"
    
    set -o pipefail
    
    if [[ $EXTRACT_EXIT -ne 0 ]]; then
        echo "  ✗ Extraction failed with exit code: $EXTRACT_EXIT"
        continue
    fi
    
    echo "  → Verifying sequence was added..."
    
    # Verify sequence was added
    CURRENT_SEQ_COUNT=$(grep -c "^>" "$BATCH_ALIGN_TMP" 2>/dev/null || echo 0)
    echo "  → Sequence count in file: $CURRENT_SEQ_COUNT (previously: $ALIGN_COUNT)"
    
    if [[ $CURRENT_SEQ_COUNT -gt $ALIGN_COUNT ]]; then
        echo "  → Count increased, incrementing counter..."
        ALIGN_COUNT=$((ALIGN_COUNT + 1))
        echo "  → New count: $ALIGN_COUNT"
        echo "  ✓ Extracted sequence ($ALIGN_COUNT total)"
    else
        echo "  ✗ Sequence count not increased"
    fi
    echo "  → Done processing $seq_id"
done

echo ""
echo "==================== Loop Complete ===================="
echo "Extracted $ALIGN_COUNT sequences into batch alignment"
echo ""

if [[ ! -f "$BATCH_ALIGN_TMP" ]]; then
    echo "ERROR: Batch alignment file was not created: $BATCH_ALIGN_TMP"
    exit 1
fi

if [[ ! -s "$BATCH_ALIGN_TMP" ]]; then
    echo "ERROR: Batch alignment file is empty: $BATCH_ALIGN_TMP"
    rm -f "$BATCH_ALIGN_TMP"
    exit 1
fi

if [[ $ALIGN_COUNT -lt 2 ]]; then
    echo "ERROR: Need at least 2 sequences for batch analysis. Got: $ALIGN_COUNT"
    rm -f "$BATCH_ALIGN_TMP"
    exit 1
fi

echo "Batch alignment file ready: $BATCH_ALIGN_TMP"
echo "File size: $(wc -c < "$BATCH_ALIGN_TMP") bytes"
echo ""

# ────────────────────────────────────────────────────────────────────────────
# Step 2: Multiple sequence alignment
# ────────────────────────────────────────────────────────────────────────────

echo ""
echo "Step 2: Running MAFFT alignment..."

BATCH_ALIGN_ALIGNED="$BATCH_TREES/batch.aligned.fasta"
mafft --auto "$BATCH_ALIGN_TMP" > "$BATCH_ALIGN_ALIGNED"

if [[ ! -f "$BATCH_ALIGN_ALIGNED" ]]; then
    echo "ERROR: MAFFT failed to generate alignment"
    rm -f "$BATCH_ALIGN_TMP"
    exit 1
fi

echo "Alignment saved: $BATCH_ALIGN_ALIGNED"
rm -f "$BATCH_ALIGN_TMP"

# ────────────────────────────────────────────────────────────────────────────
# Step 3: Phylogenetic inference
# ────────────────────────────────────────────────────────────────────────────

echo ""
echo "Step 3: Building phylogenetic tree with IQ-TREE..."

# Clean up old checkpoint files from previous runs to avoid conflicts
rm -f "$BATCH_ALIGN_ALIGNED.ckp.gz" "$BATCH_ALIGN_ALIGNED.ckp"

iqtree \
    -s "$BATCH_ALIGN_ALIGNED" \
    -m JC \
    -nt AUTO \
    -fast \
    -redo \
    -quiet

echo "Tree files written to: $BATCH_TREES/"

# Verify tree file
if [[ ! -f "$BATCH_ALIGN_ALIGNED.treefile" ]]; then
    echo "ERROR: IQ-TREE failed to generate tree"
    exit 1
fi

cp "$BATCH_ALIGN_ALIGNED.treefile" "$BATCH_TREES/tree.treefile"
echo "Batch tree saved: $BATCH_TREES/tree.treefile"

# ────────────────────────────────────────────────────────────────────────────
# Step 4: SNP distance matrix
# ────────────────────────────────────────────────────────────────────────────

echo ""
echo "Step 4: Computing SNP distance matrix..."

# Use R to compute pairwise SNP distances
conda run -n R_shared Rscript - "$BATCH_ALIGN_ALIGNED" "$BATCH_SNP" << 'EOF'
args <- commandArgs(trailingOnly = TRUE)
align_file <- args[1]
output_dir <- args[2]

library(ape)

# Read alignment
aln <- tryCatch({
    read.dna(align_file, format = "fasta", as.character = TRUE)
}, error = function(e) {
    cat("ERROR reading alignment:", e$message, "\n")
    NULL
})

if (is.null(aln) || nrow(aln) < 2) {
    cat("ERROR: Alignment must have at least 2 sequences\n")
    q(save = "no", status = 1)
}

# Compute pairwise SNP distances
n_seqs <- nrow(aln)
seq_ids <- rownames(aln)
snp_mat <- matrix(0L, n_seqs, n_seqs, dimnames = list(seq_ids, seq_ids))

for (i in 1:(n_seqs-1)) {
    for (j in (i+1):n_seqs) {
        s1 <- aln[i, ]
        s2 <- aln[j, ]
        valid <- s1 != "-" & s2 != "-" & !is.na(s1) & !is.na(s2)
        d <- sum(s1[valid] != s2[valid])
        snp_mat[i, j] <- snp_mat[j, i] <- d
    }
}

# Save as TSV
output_file <- file.path(output_dir, "batch_snp_distances.tsv")
write.table(snp_mat, file = output_file, sep = "\t", quote = FALSE)
cat("SNP distance matrix saved:", output_file, "\n")
EOF

if [[ ! -f "$BATCH_SNP/batch_snp_distances.tsv" ]]; then
    echo "WARNING: SNP distance matrix computation failed or was skipped"
else
    echo "SNP distance matrix computed successfully"
fi

# ────────────────────────────────────────────────────────────────────────────
# Completion
# ────────────────────────────────────────────────────────────────────────────

echo ""
echo "================================================"
echo "Batch analysis complete!"
echo "================================================"
echo ""
echo "Output files:"
echo "  - Batch alignment:      $BATCH_ALIGN_ALIGNED"
echo "  - Batch tree:           $BATCH_TREES/tree.treefile"
echo "  - SNP distances:        $BATCH_SNP/batch_snp_distances.tsv"
echo ""
echo "These files are automatically detected by batch_report.Rmd"
echo "Re-run the batch report to include batch QC visualizations."
echo ""

exit 0
